In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score,recall_score
df=pd.read_csv('/content/spam_ham_dataset.csv')
df

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

# New Section

In [ ]:
df.shape

(6420, 4)

In [ ]:
df.describe()

         label_num
count  6385.000000
mean      0.293344
std       0.455330
min       0.000000
25%       0.000000
50%       0.000000
75%       1.000000
max       1.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6420 entries, 0 to 6419
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  6420 non-null   object
 1   label       6396 non-null   object
 2   text        6389 non-null   object
 3   label_num   6385 non-null   float64
dtypes: float64(1), object(3)
memory usage: 200.8+ KB

In [ ]:
df.head()

,Unnamed: 0,label,text,label_num
0,605,ham,Subject: enron methanol ; meter # : 988291\r\n...,0.0
1,2349,ham,"Subject: hpl nom for january 9 , 2001\r\n( see...",0.0
2,3624,ham,"Subject: neon retreat\r\nho ho ho , we ' re ar...",0.0
3,4685,spam,"Subject: photoshop , windows , office . cheap ...",1.0
4,2030,ham,Subject: re : indian springs\r\nthis deal is t...,0.0

In [ ]:
df.tail()

,Unnamed: 0,label,text,label_num
6415,1518,ham,Subject: put the 10 on the ft\r\nthe transport...,0.0
6416,404,ham,Subject: 3 / 4 / 2000 and following noms\r\nhp...,0.0
6417,2933,ham,Subject: calpine daily gas nomination\r\n>\r\n...,0.0
6418,1409,ham,Subject: industrial worksheets for august 2000...,0.0
6419,4807,spam,Subject: important online banking alert\r\ndea...,1.0

In [ ]:
df.isnull().sum()

Unnamed: 0     0
label         24
text          31
label_num     35
dtype: int64

In [ ]:
q=df['label'].mode()

In [ ]:
q[0]

'ham'

In [ ]:
df['label'].fillna(df['label'].mode()[0])

0        ham
1        ham
2        ham
3       spam
4        ham
        ...
6415     ham
6416     ham
6417     ham
6418     ham
6419    spam
Name: label, Length: 6420, dtype: object

In [ ]:
df['label'].fillna(df['label'].mode()[0],inplace=True)
df

,Unnamed: 0,label,text,label_num
0,605,ham,Subject: enron methanol ; meter # : 988291\r\n...,0.0
1,2349,ham,"Subject: hpl nom for january 9 , 2001\r\n( see...",0.0
2,3624,ham,"Subject: neon retreat\r\nho ho ho , we ' re ar...",0.0
3,4685,spam,"Subject: photoshop , windows , office . cheap ...",1.0
4,2030,ham,Subject: re : indian springs\r\nthis deal is t...,0.0
...,...,...,...,...
6415,1518,ham,Subject: put the 10 on the ft\r\nthe transport...,0.0
6416,404,ham,Subject: 3 / 4 / 2000 and following noms\r\nhp...,0.0
6417,2933,ham,Subject: calpine daily gas nomination\r\n>\r\n...,0.0
6418,1409,ham,Subject: industrial worksheets for august 2000...,0.0
6419,4807,spam,Subject: important online banking alert\r\ndea...,1.0

In [ ]:
df.text.fillna(df.text.mode()[0])

0       Subject: enron methanol ; meter # : 988291\r\n...
1       Subject: hpl nom for january 9 , 2001\r\n( see...
2       Subject: neon retreat\r\nho ho ho , we ' re ar...
3       Subject: photoshop , windows , office . cheap ...
4       Subject: re : indian springs\r\nthis deal is t...
                              ...
6415    Subject: put the 10 on the ft\r\nthe transport...
6416    Subject: 3 / 4 / 2000 and following noms\r\nhp...
6417    Subject: calpine daily gas nomination\r\n>\r\n...
6418    Subject: industrial worksheets for august 2000...
6419    Subject: important online banking alert\r\ndea...
Name: text, Length: 6420, dtype: object

In [ ]:
df.text.fillna(df.text.mode()[0],inplace=True)
df

,Unnamed: 0,label,text,label_num
0,605,ham,Subject: enron methanol ; meter # : 988291\r\n...,0.0
1,2349,ham,"Subject: hpl nom for january 9 , 2001\r\n( see...",0.0
2,3624,ham,"Subject: neon retreat\r\nho ho ho , we ' re ar...",0.0
3,4685,spam,"Subject: photoshop , windows , office . cheap ...",1.0
4,2030,ham,Subject: re : indian springs\r\nthis deal is t...,0.0
...,...,...,...,...
6415,1518,ham,Subject: put the 10 on the ft\r\nthe transport...,0.0
6416,404,ham,Subject: 3 / 4 / 2000 and following noms\r\nhp...,0.0
6417,2933,ham,Subject: calpine daily gas nomination\r\n>\r\n...,0.0
6418,1409,ham,Subject: industrial worksheets for august 2000...,0.0
6419,4807,spam,Subject: important online banking alert\r\ndea...,1.0

In [ ]:
df.iloc[:,:]

,Unnamed: 0,label,text,label_num
0,605,ham,Subject: enron methanol ; meter # : 988291\r\n...,0.0
1,2349,ham,"Subject: hpl nom for january 9 , 2001\r\n( see...",0.0
2,3624,ham,"Subject: neon retreat\r\nho ho ho , we ' re ar...",0.0
3,4685,spam,"Subject: photoshop , windows , office . cheap ...",1.0
4,2030,ham,Subject: re : indian springs\r\nthis deal is t...,0.0
...,...,...,...,...
6415,1518,ham,Subject: put the 10 on the ft\r\nthe transport...,0.0
6416,404,ham,Subject: 3 / 4 / 2000 and following noms\r\nhp...,0.0
6417,2933,ham,Subject: calpine daily gas nomination\r\n>\r\n...,0.0
6418,1409,ham,Subject: industrial worksheets for august 2000...,0.0
6419,4807,spam,Subject: important online banking alert\r\ndea...,1.0

In [ ]:
df.iloc[:,0:3]

     Unnamed: 0 label                                               text
0           605   ham  Subject: enron methanol ; meter # : 988291\r\n...
1          2349   ham  Subject: hpl nom for january 9 , 2001\r\n( see...
2          3624   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...
3          4685  spam  Subject: photoshop , windows , office . cheap ...
4          2030   ham  Subject: re : indian springs\r\nthis deal is t...
...         ...   ...                                                ...
6415       1518   ham  Subject: put the 10 on the ft\r\nthe transport...
6416        404   ham  Subject: 3 / 4 / 2000 and following noms\r\nhp...
6417       2933   ham  Subject: calpine daily gas nomination\r\n>\r\n...
6418       1409   ham  Subject: industrial worksheets for august 2000...
6419       4807  spam  Subject: important online banking alert\r\ndea...

[6420 rows x 3 columns]

In [ ]:
df.columns

Index(['Unnamed: 0', 'label', 'text', 'label_num'], dtype='object')

In [ ]:
df.label_num.value_counts()

0.0    4512
1.0    1873
Name: label_num, dtype: int64

In [ ]:
df.label.value_counts()

ham                                                 4536
spam                                                1873
 white and blue out ""                                 1
 a red                                                 1
 just like the maroon out games for the osu            1
 what better statement can we aggies make              1
 and our patriotic nature                              1
 ""                                                    1
 and we celebrate                                      1
 and our support for all the heroes                    1
 and the aggie spirit is still alive . god bless       1
 the free nation .                                     1
0                                                      1
Name: label, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
from collections import Counter as count
le=LabelEncoder()
print('before label encoding',count(df['label']))
df['label']=le.fit_transform(df['label'])
print('after r as eplace',count(df['label']))

before label encoding Counter({'ham': 4536, 'spam': 1873, ' white and blue out ""': 1, ' a red ': 1, ' just like the maroon out games for the osu': 1, ' what better statement can we aggies make ': 1, ' and our patriotic nature ': 1, ' ""': 1, ' and we celebrate': 1, ' and our support for all the heroes ': 1, ' and the aggie spirit is still alive . god bless': 1, ' the free nation .': 1, '0': 1})
after r as eplace Counter({11: 4536, 12: 1873, 9: 1, 1: 1, 6: 1, 8: 1, 2: 1, 0: 1, 5: 1, 3: 1, 4: 1, 7: 1, 10: 1})

In [ ]:
print('before replace',count(df['label_num']))
df['label_num']=df['label_num'].replace(['0','1'],[0.0,1.0])
print('after replace',count(df['label_num']))

before replace Counter({0.0: 4512, 1.0: 1873, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1})
after replace Counter({0.0: 4512, 1.0: 1873, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1, nan: 1})

In [ ]:
df.shape

(6420, 4)

In [ ]:
df.columns

Index(['Unnamed: 0', 'label', 'text', 'label_num'], dtype='object')

In [ ]:
df

     Unnamed: 0  label  text  label_num
0           605     11  1213        0.0
1          2349     11  1989        0.0
2          3624     11  2778        0.0
3          4685     12  3162        1.0
4          2030     11  3617        0.0
...         ...    ...   ...        ...
6415       1518     11  3258        0.0
6416        404     11   129        0.0
6417       2933     11   499        0.0
6418       1409     11  2227        0.0
6419       4807     12  2199        1.0

[6420 rows x 4 columns]

In [ ]:
x=df.drop(['label_num'],axis=1)
x

     Unnamed: 0  label  text
0           605     11  1213
1          2349     11  1989
2          3624     11  2778
3          4685     12  3162
4          2030     11  3617
...         ...    ...   ...
6415       1518     11  3258
6416        404     11   129
6417       2933     11   499
6418       1409     11  2227
6419       4807     12  2199

[6420 rows x 3 columns]

In [ ]:
y=df['label_num']
y

0       0.0
1       0.0
2       0.0
3       1.0
4       0.0
       ...
6415    0.0
6416    0.0
6417    0.0
6418    0.0
6419    1.0
Name: label_num, Length: 6420, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(x_test.shape)

(5136, 3)
(5136,)
(1284, 3)
(1284, 3)

In [ ]:
x_train

     Unnamed: 0  label  text
1031       4875     12   681
4328       2373     11   530
2709       1665     11  2088
189        3510     11  3205
4858       1215     11  1077
...         ...    ...   ...
4931       3498     11   653
3264        985     11   734
1653       4394     12  1351
2607       3426     11  1362
2732       2310     11  4493

[5136 rows x 3 columns]

In [ ]:
x_test

     Unnamed: 0  label  text
148         541     11  2815
1547        347     11  4269
3519       1361     11  4150
5128       3718     12  1297
5985        637     11  3105
...         ...    ...   ...
3994       1571     11  2350
5549        956     11  4588
2726       1686     11  1154
1891        246     11   170
4235       1632     11   918

[1284 rows x 3 columns]

In [ ]:
y_train

1031    1.0
4328    0.0
2709    0.0
189     0.0
4858    0.0
       ...
4931    0.0
3264    0.0
1653    1.0
2607    0.0
2732    0.0
Name: label_num, Length: 5136, dtype: float64

In [ ]:
y_test

148     0.0
1547    0.0
3519    0.0
5128    1.0
5985    0.0
       ...
3994    0.0
5549    0.0
2726    0.0
1891    0.0
4235    0.0
Name: label_num, Length: 1284, dtype: float64

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
dt=KNeighborsClassifier(n_neighbors=7)
dt.fit(x_train,y_train)
yPred=dt.predict(x_test)
yPred_train=dt.predict(x_train)
print("Confusion Matrix")
print(confusion_matrix(y_test,yPred))
print("Classification Report")
print(classification_report(y_test,yPred))

ValueError: ignored